# Generated by Django 5.1.4 on 2025-01-06 21:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import temba.orgs.models
import temba.utils.uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("channels", "0187_squashed"),
        ("orgs", "0162_squashed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this item is active, use this instead of deleting",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this item was originally created",
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this item was last modified",
                    ),
                ),
                ("uuid", models.UUIDField(default=temba.utils.uuid.uuid4, unique=True)),
                ("is_system", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=512)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="The user which originally created this item",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_creations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        help_text="The user which last modified this item",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_modifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="templates",
                        to="orgs.org",
                    ),
                ),
            ],
            bases=(models.Model, temba.orgs.models.DependencyMixin),
        ),
        migrations.CreateModel(
            name="TemplateTranslation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("locale", models.CharField(max_length=6)),
                ("components", models.JSONField(default=list)),
                ("variables", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "Pending"),
                            ("A", "Approved"),
                            ("R", "Rejected"),
                            ("U", "Paused"),
                            ("D", "Disabled"),
                            ("I", "In Appeal"),
                        ],
                        default="P",
                        max_length=1,
                    ),
                ),
                ("namespace", models.CharField(default="", max_length=36)),
                ("external_id", models.CharField(max_length=64, null=True)),
                ("external_locale", models.CharField(max_length=6, null=True)),
                ("is_supported", models.BooleanField(default=True)),
                ("is_compatible", models.BooleanField(default=True)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="template_translations",
                        to="channels.channel",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="translations",
                        to="templates.template",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="template",
            name="base_translation",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="base_template",
                to="templates.templatetranslation",
            ),
        ),
        migrations.AddConstraint(
            model_name="templatetranslation",
            constraint=models.UniqueConstraint(
                fields=("template", "channel", "locale"),
                name="templatetranslations_unique",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="template",
            unique_together={("org", "name")},
        ),
    ]
