# Generated by Django 5.2.2 on 2025-07-02 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("channels", "0207_squashed"),
        ("orgs", "0172_squashed"),
        ("templates", "0046_squashed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="created_by",
            field=models.ForeignKey(
                help_text="The user which originally created this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_creations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="modified_by",
            field=models.ForeignKey(
                help_text="The user which last modified this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_modifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="templates",
                to="orgs.org",
            ),
        ),
        migrations.AddField(
            model_name="templatetranslation",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="template_translations",
                to="channels.channel",
            ),
        ),
        migrations.AddField(
            model_name="templatetranslation",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="translations",
                to="templates.template",
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="base_translation",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="base_template",
                to="templates.templatetranslation",
            ),
        ),
        migrations.AddConstraint(
            model_name="templatetranslation",
            constraint=models.UniqueConstraint(
                fields=("template", "channel", "locale"),
                name="templatetranslations_unique",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="template",
            unique_together={("org", "name")},
        ),
    ]
