# Generated by Django 5.1.4 on 2025-01-06 21:25

import django.utils.timezone
from django.db import migrations, models

import temba.utils.uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AirtimeTransfer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=temba.utils.uuid.uuid4, unique=True)),
                (
                    "status",
                    models.CharField(choices=[("S", "Success"), ("F", "Failed")], max_length=1),
                ),
                ("external_id", models.CharField(max_length=255, null=True)),
                ("recipient", models.CharField(max_length=255)),
                ("sender", models.CharField(max_length=255, null=True)),
                ("currency", models.CharField(max_length=32, null=True)),
                (
                    "desired_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("actual_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
