# Generated by Django 5.2.2 on 2025-07-02 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("airtime", "0035_squashed"),
        ("contacts", "0207_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="airtimetransfer",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="airtime_transfers",
                to="contacts.contact",
            ),
        ),
    ]
