# Generated by Django 5.2.2 on 2025-08-11 19:32

from itertools import batched

from django.db import migrations

from temba.utils.uuid import is_uuid7, uuid7


def update_transfer_uuids(apps, schema_editor):
    AirtimeTransfer = apps.get_model("airtime", "AirtimeTransfer")

    num_updated = 0

    for batch in batched(AirtimeTransfer.objects.order_by("id"), 100):
        updated = []
        for transfer in batch:
            if not is_uuid7(transfer.uuid):
                transfer.uuid = uuid7(transfer.created_on)
                updated.append(transfer)
                num_updated += 1

        if updated:
            AirtimeTransfer.objects.bulk_update(updated, ["uuid"])
            print(f"Updated {num_updated} airtime transfer records with new v7 UUIDs")


class Migration(migrations.Migration):

    dependencies = [
        ("airtime", "0037_squashed"),
    ]

    operations = [
        migrations.RunPython(update_transfer_uuids, reverse_code=migrations.RunPython.noop),
    ]
