# Generated by Django 5.1.2 on 2025-01-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0028_squashed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="repeat_period",
            field=models.CharField(
                choices=[
                    ("O", "Never"),
                    ("D", "Daily"),
                    ("W", "Weekly"),
                    ("M", "Monthly"),
                    ("Y", "Yearly"),
                ],
                max_length=1,
            ),
        ),
    ]
