# Generated by Django 4.0.7 on 2022-11-01 18:30

from django.conf import settings
from django.db import migrations


def get_configured_brands():  # pragma: no cover
    for brand in settings.BRANDS:
        yield None, brand

    for key, brand in getattr(settings, "BRANDING", {}).items():
        yield key, brand


def brand_matches(lookup: str, key: str | None, brand: dict) -> bool:  # pragma: no cover
    identifiers = {key, brand.get("slug"), brand.get("domain")}
    identifiers.update(brand.get("hosts") or [])
    return lookup in identifiers


def get_branding(host: str) -> dict:  # pragma: no cover
    """
    Returns the branding for the given host
    """
    brands = list(get_configured_brands())

    for lookup in (host, settings.DEFAULT_BRAND):
        for key, brand in brands:
            if brand_matches(lookup, key, brand):
                return brand

    return brands[0][1]


def convert_org_brands_to_slugs(apps, schema_editor):  # pragma: no cover
    Org = apps.get_model("orgs", "Org")
    for org in Org.objects.all():
        org.brand = get_branding(org.brand)["slug"]
        org.save(update_fields=("brand",))


def reverse(apps, schewma_editor):  # pragma: no cover
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0102_alter_org_brand_alter_org_plan"),
    ]

    operations = [migrations.RunPython(convert_org_brands_to_slugs, reverse)]
