# Generated by Django 5.1.4 on 2025-01-08 20:51

from django.db import migrations


def remove_viewers(apps, schema_editor):  # pragma: no cover
    OrgMembership = apps.get_model("orgs", "OrgMembership")
    num_deleted = OrgMembership.objects.filter(role_code="V").delete()[0]
    if num_deleted:
        print(f"Deleted {num_deleted} viewer memberships")


class Migration(migrations.Migration):

    dependencies = [("orgs", "0163_squashed")]

    operations = [migrations.RunPython(remove_viewers, migrations.RunPython.noop)]
