# Generated by Django 5.1.4 on 2025-01-16 18:54

from django.db import migrations


def grant_prometheus_feature(apps, schema_editor):  # pragma: no cover
    Org = apps.get_model("orgs", "Org")

    num_updated = 0
    for org in Org.objects.exclude(prometheus_token=None):
        org.features += ["prometheus"]
        org.save(update_fields=("features",))
        num_updated += 1

    if num_updated:
        print(f"Granted prometheus feature to {num_updated} orgs with existing tokens")


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0164_remove_viewers"),
    ]

    operations = [migrations.RunPython(grant_prometheus_feature, migrations.RunPython.noop)]
