# Generated by Django 5.1.4 on 2025-01-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0165_grant_prometheus_feature"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgmembership",
            name="last_seen_on",
            field=models.DateTimeField(null=True),
        ),
    ]
