# Generated by Django 5.1.4 on 2025-02-12 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0168_delete_backuptoken"),
        ("users", "0007_backfill_new_user_fields"),
    ]

    operations = [
        migrations.DeleteModel(name="UserSettings"),
    ]
