# Generated by Django 5.1.4 on 2025-04-15 18:38

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0169_delete_usersettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyCount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("count", models.IntegerField()),
                ("is_squashed", models.BooleanField(default=False)),
                ("scope", models.CharField(max_length=128)),
                ("day", models.DateField()),
                (
                    "org",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="daily_counts",
                        to="orgs.org",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        models.F("org"),
                        models.F("day"),
                        django.contrib.postgres.indexes.OpClass("scope", name="varchar_pattern_ops"),
                        name="orgdailycount_org_scope",
                    ),
                    models.Index(
                        condition=models.Q(("is_squashed", False)),
                        fields=["org", "day", "scope"],
                        name="orgdailycount_unsquashed",
                    ),
                ],
            },
        ),
    ]
