# Generated by Django 5.2.6 on 2025-10-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0172_squashed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailycount",
            name="count",
            field=models.BigIntegerField(),
        ),
    ]
