# Generated by Django 5.2.6 on 2025-10-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0173_alter_dailycount_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemcount",
            name="count",
            field=models.BigIntegerField(),
        ),
    ]
