# Generated by Django 5.2.8 on 2025-11-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0174_alter_itemcount_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="org",
            name="api_rates",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="org",
            name="limits",
            field=models.JSONField(default=dict),
        ),
    ]
