# Generated by Django 5.2.9 on 2025-12-18 15:34

from django.db import migrations, models

import temba.utils.uuid


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0175_alter_org_api_rates_alter_org_limits"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgimport",
            name="uuid",
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name="orgimport",
            name="uuid",
            field=models.UUIDField(default=temba.utils.uuid.uuid4, null=True),
        ),
    ]
