# Generated by Django 5.2.9 on 2025-12-18 16:35

import itertools
from uuid import uuid4

from django.db import migrations


def backfill_import_uuids(apps, schema_editor):  # pragma: no cover
    OrgImport = apps.get_model("orgs", "OrgImport")

    num_updated = 0

    for batch in itertools.batched(OrgImport.objects.filter(uuid__isnull=True).order_by("id"), 100):
        for imp in batch:
            imp.uuid = uuid4()
            num_updated += 1

        OrgImport.objects.bulk_update(batch, ["uuid"])
        print(f"Updated {num_updated} org import records with UUIDs")


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0176_orgimport_uuid"),
    ]

    operations = [
        migrations.RunPython(backfill_import_uuids, migrations.RunPython.noop),
    ]
