# Generated by Django 5.1.4 on 2025-01-06 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classifiers", "0014_squashed"),
        ("orgs", "0162_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="classifier",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="classifiers",
                to="orgs.org",
            ),
        ),
        migrations.AddField(
            model_name="intent",
            name="classifier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="intents",
                to="classifiers.classifier",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="intent",
            unique_together={("classifier", "external_id")},
        ),
    ]
