# Generated by Django 5.1.4 on 2025-01-06 21:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Archive",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archive_type",
                    models.CharField(choices=[("message", "Message"), ("run", "Run")], max_length=16),
                ),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "period",
                    models.CharField(
                        choices=[("D", "Day"), ("M", "Month")],
                        default="D",
                        max_length=1,
                    ),
                ),
                ("start_date", models.DateField()),
                ("record_count", models.IntegerField(default=0)),
                ("size", models.BigIntegerField(default=0)),
                ("hash", models.TextField()),
                ("url", models.URLField()),
                ("build_time", models.IntegerField()),
                ("needs_deletion", models.BooleanField(default=False)),
                ("deleted_on", models.DateTimeField(null=True)),
            ],
        ),
    ]
