# Generated by Django 5.2.2 on 2025-07-02 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("archives", "0023_squashed"),
        ("orgs", "0171_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="archive",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="archives",
                to="orgs.org",
            ),
        ),
        migrations.AddField(
            model_name="archive",
            name="rollup",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="archives.archive",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="archive",
            unique_together={("org", "archive_type", "start_date", "period")},
        ),
    ]
