# Generated by Django 5.2.8 on 2025-11-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archives", "0024_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="archive",
            name="location",
            field=models.CharField(max_length=1088, null=True),
        ),
    ]
