# Generated by Django 5.2.8 on 2025-11-24 21:37

from urllib.parse import urlparse

from django.db import migrations


def backfill_archive_location(apps, schema_editor):  # pragma: no cover
    Archive = apps.get_model("archives", "Archive")

    print(f"Backfilling location on {Archive.objects.filter(location__isnull=True).count()} archives...")
    num_updated = 0

    while True:
        batch = list(Archive.objects.filter(location__isnull=True)[:1000])
        if not batch:
            break

        for archive in batch:
            url_parts = urlparse(archive.url)
            bucket, key = url_parts.netloc.split(".")[0], url_parts.path[1:]

            archive.location = f"{bucket}:{key}"

        Archive.objects.bulk_update(batch, ["location"])
        num_updated += len(batch)
        print(f" > updated {num_updated} archive locations")


def apply_manual():  # pragma: no cover
    from django.apps import apps

    backfill_archive_location(apps, None)


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("archives", "0025_archive_location"),
    ]

    operations = [
        migrations.RunPython(backfill_archive_location, reverse_code=migrations.RunPython.noop),
    ]
