# Generated by Django 5.2.8 on 2025-11-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archives", "0026_backfill_archive_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archive",
            name="location",
            field=models.CharField(max_length=1088),
        ),
        migrations.AlterField(
            model_name="archive",
            name="url",
            field=models.URLField(null=True),
        ),
    ]
