# Generated by Django 5.2.8 on 2025-11-26 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("archives", "0027_alter_archive_location_alter_archive_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="archive",
            name="url",
        ),
    ]
