# Generated by Django 5.2.8 on 2025-12-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archives", "0028_remove_archive_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archive",
            name="location",
            field=models.CharField(max_length=1088, null=True),
        ),
    ]
