# Generated by Django 5.2.8 on 2025-12-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archives", "0029_alter_archive_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="archive",
            name="uuid",
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name="archive",
            name="hash",
            field=models.TextField(null=True),
        ),
    ]
