# Generated by Django 5.2.9 on 2025-12-15 19:52

from collections import defaultdict

from django.core.files.storage import storages
from django.db import migrations


def delete_rolled_up_archives(apps, schema_editor):
    Archive = apps.get_model("archives", "Archive")
    s3_client = storages["archives"].connection.meta.client

    purged_rollups = Archive.objects.filter(needs_deletion=False).exclude(rollup=None)

    print(f"Deleting {purged_rollups.count()} rolled up and purged/empty archives...")
    num_deleted = 0

    while True:
        batch = list(purged_rollups[:1000])
        if not batch:
            break

        s3_files = defaultdict(list)
        for archive in batch:
            assert archive.rollup_id is not None
            assert not archive.needs_deletion

            if archive.location:
                bucket, key = archive.location.split(":", 1)
                s3_files[bucket].append(key)

        for bucket, keys in s3_files.items():
            s3_client.delete_objects(Bucket=bucket, Delete={"Objects": [{"Key": key} for key in keys]})

        Archive.objects.filter(id__in=[a.id for a in batch]).delete()
        num_deleted += len(batch)
        print(f" > deleted {num_deleted} rolled up archives")


def apply_manual():  # pragma: no cover
    from django.apps import apps

    delete_rolled_up_archives(apps, None)


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("archives", "0030_archive_uuid_alter_archive_hash"),
    ]

    operations = [
        migrations.RunPython(delete_rolled_up_archives, reverse_code=migrations.RunPython.noop),
    ]
