# Generated by Django 5.2.9 on 2025-12-16 16:18

import itertools

from django.db import migrations

from temba.utils.uuid import uuid7


def backfill_archive_uuids(apps, schema_editor):  # pragma: no cover
    Archive = apps.get_model("archives", "Archive")

    num_updated = 0

    for batch in itertools.batched(Archive.objects.filter(uuid__isnull=True).order_by("id"), 100):
        for archive in batch:
            archive.uuid = uuid7(archive.created_on)
            num_updated += 1

        Archive.objects.bulk_update(batch, ["uuid"])
        print(f"Updated {num_updated} archive records with new v7 UUIDs")


def apply_manual():  # pragma: no cover
    from django.apps import apps

    backfill_archive_uuids(apps, None)


class Migration(migrations.Migration):

    dependencies = [
        ("archives", "0031_delete_rolled_up"),
    ]

    operations = [
        migrations.RunPython(backfill_archive_uuids, migrations.RunPython.noop),
    ]
