# Generated by Django 5.2.9 on 2025-12-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archives", "0032_backfill_uuids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archive",
            name="uuid",
            field=models.UUIDField(unique=True),
        ),
    ]
