# Generated by Django 5.1.4 on 2025-01-06 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campaigns", "0062_squashed"),
        ("contacts", "0197_squashed"),
        ("flows", "0352_squashed"),
        ("orgs", "0162_squashed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="campaigns",
                to="orgs.org",
            ),
        ),
        migrations.AddField(
            model_name="campaignevent",
            name="campaign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="campaigns.campaign",
            ),
        ),
        migrations.AddField(
            model_name="campaignevent",
            name="created_by",
            field=models.ForeignKey(
                help_text="The user which originally created this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_creations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="campaignevent",
            name="flow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="campaign_events",
                to="flows.flow",
            ),
        ),
        migrations.AddField(
            model_name="campaignevent",
            name="modified_by",
            field=models.ForeignKey(
                help_text="The user which last modified this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_modifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="campaignevent",
            name="relative_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="campaign_events",
                to="contacts.contactfield",
            ),
        ),
        migrations.AddField(
            model_name="eventfire",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="campaign_fires",
                to="contacts.contact",
            ),
        ),
        migrations.AddField(
            model_name="eventfire",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fires",
                to="campaigns.campaignevent",
            ),
        ),
        migrations.AddIndex(
            model_name="eventfire",
            index=models.Index(
                condition=models.Q(("fired", None)),
                fields=["scheduled"],
                name="eventfires_unfired",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventfire",
            constraint=models.UniqueConstraint(
                condition=models.Q(("fired", None)),
                fields=("event_id", "contact_id"),
                name="eventfires_unfired_unique",
            ),
        ),
    ]
