# Generated by Django 5.1.4 on 2025-02-10 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0064_convert_eventfires"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EventFire",
        ),
    ]
