# Generated by Django 5.1.4 on 2025-02-12 16:10

from django.db import migrations

import temba.utils.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0065_delete_eventfire"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignevent",
            name="message",
            field=temba.utils.models.fields.TranslatableField(max_length=4096, null=True),
        ),
    ]
