# Generated by Django 5.1.4 on 2025-03-04 00:03

from django.db import migrations
from django.db.models import F, Value
from django.db.models.functions import Concat


def add_version_to_event_fires(apps, schema_editor):  # pragma: no cover
    ContactFire = apps.get_model("contacts", "ContactFire")

    num_updated = 0

    while True:
        batch = list(ContactFire.objects.filter(fire_type="C").exclude(scope__contains=":")[:1000])
        if not batch:
            break

        ContactFire.objects.filter(id__in=[f.id for f in batch]).update(scope=Concat(F("scope"), Value(":1")))
        num_updated += len(batch)

        print(f"Updated {num_updated} contact fires for campaign events")


def apply_manual():  # pragma: no cover
    from django.apps import apps

    add_version_to_event_fires(apps, None)


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0067_campaignevent_status"),
    ]

    operations = [
        migrations.RunPython(add_version_to_event_fires, migrations.RunPython.noop),
    ]
