# Generated by Django 5.1.4 on 2025-03-12 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0071_backfill_fire_counts"),
    ]

    operations = [
        migrations.AddField(model_name="campaignevent", name="translations", field=models.JSONField(null=True)),
    ]
