# Generated by Django 5.1.4 on 2025-03-12 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0072_campaignevent_translations"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignevent", name="base_language", field=models.CharField(max_length=3, null=True)
        ),
    ]
