# Generated by Django 5.1.4 on 2025-03-12 00:57

from django.db import migrations


def backfill_campaignevent_translations(apps, schema_editor):  # pragma: no cover
    CampaignEvent = apps.get_model("campaigns", "CampaignEvent")

    num_updated = 0
    while True:
        batch = CampaignEvent.objects.filter(message__isnull=False, translations__isnull=True).select_related("flow")[
            :500
        ]
        if not batch:
            break

        for event in batch:
            event.translations = {lang: {"text": text} for lang, text in event.message.items()}
            event.base_language = event.flow.base_language
            event.save(update_fields=("translations", "base_language"))

        num_updated += len(batch)
        print(f"Backfilled translations for {num_updated} campaign events...")


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0073_campaignevent_base_language"),
    ]

    operations = [
        migrations.RunPython(backfill_campaignevent_translations, migrations.RunPython.noop),
    ]
