# Generated by Django 5.1.4 on 2025-03-13 18:37

from django.db import migrations

import temba.utils.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0074_backfill_campaignevent_translations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaignevent",
            name="message",
            field=temba.utils.models.fields.TranslatableField(blank=True, max_length=4096, null=True),
        ),
    ]
