# Generated by Django 5.1.4 on 2025-03-13 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0075_alter_campaignevent_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaignevent",
            name="message",
        ),
    ]
