# Generated by Django 5.1.4 on 2025-03-14 00:33

from django.db import migrations
from django.utils import timezone

from temba.utils.uuid import uuid4


def _deleted_name(flow) -> str:  # pragma: no cover
    return f"deleted-{uuid4()}-{flow.name}"[:64]


def remove_single_message_flows(apps, schema_editor):  # pragma: no cover
    CampaignEvent = apps.get_model("campaigns", "CampaignEvent")
    Flow = apps.get_model("flows", "Flow")

    num_updated = 0

    while True:
        batch = list(CampaignEvent.objects.filter(event_type="M", flow__isnull=False)[:1000])
        if not batch:
            break

        for flow in Flow.objects.filter(id__in=[e.flow_id for e in batch], is_system=True):
            flow.field_dependencies.clear()
            flow.counts.all().delete()
            flow.name = _deleted_name(flow)
            flow.modified_on = timezone.now()
            flow.is_active = False
            flow.save(update_fields=("name", "modified_on", "is_active"))

        CampaignEvent.objects.filter(id__in=[e.id for e in batch]).update(flow=None)
        num_updated += len(batch)

        print(f"Removed {num_updated} single message flows")


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0077_alter_campaignevent_flow"),
    ]

    operations = [
        migrations.RunPython(remove_single_message_flows, reverse_code=migrations.RunPython.noop),
    ]
