# Generated by Django 5.1.4 on 2025-02-11 20:40

from django.db import migrations


def copy_backup_tokens(apps, schema_editor):  # pragma: no cover
    BackupToken = apps.get_model("users", "BackupToken")
    BackupTokenOld = apps.get_model("orgs", "BackupToken")

    num_copied = 0
    for token in BackupTokenOld.objects.all():
        BackupToken.objects.create(
            user=token.user, token=token.token, is_used=token.is_used, created_on=token.created_on
        )
        num_copied += 1

    if num_copied:
        print(f"Copied {num_copied} backup tokens from orgs app to users app")


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_backuptoken"),
    ]

    operations = [migrations.RunPython(copy_backup_tokens, migrations.RunPython.noop)]
