# Generated by Django 5.1.4 on 2025-02-11 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_copy_backup_token"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AlterModelTable(
            name="user",
            table=None,
        ),
    ]
