# Generated by Django 5.1.4 on 2025-02-11 21:13

import pyotp
import storages.backends.s3

from django.db import migrations, models

import temba.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_options_alter_user_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                null=True,
                storage=storages.backends.s3.S3Storage(
                    bucket_name="temba-default",
                    default_acl="public-read",
                    querystring_auth=False,
                    signature_version="s3v4",
                ),
                upload_to=temba.utils.fields.UploadToIdPathAndRename("avatars/"),
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_system",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[
                    ("en-us", "English"),
                    ("cs", "Czech"),
                    ("es", "Spanish"),
                    ("fr", "French"),
                    ("mn", "Mongolian"),
                    ("pt-br", "Portuguese"),
                    ("ru", "Russian"),
                ],
                default="en-us",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_auth_on",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="two_factor_secret",
            field=models.CharField(default=pyotp.random_base32, max_length=16),
        ),
        migrations.AddField(
            model_name="user",
            name="two_factor_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="email_status",
            field=models.CharField(
                choices=[("U", "Unverified"), ("V", "Verified"), ("F", "Failing")], default="U", max_length=1
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verification_secret",
            field=models.CharField(db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="external_id",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_token",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
