# Generated by Django 5.1.4 on 2025-02-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_backfill_new_user_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="two_factor_secret",
            field=models.CharField(max_length=16),
        ),
    ]
