# Generated by Django 5.1.4 on 2025-02-12 18:48

from django.db import migrations, models

from temba.utils.text import generate_secret


def ensure_email_verification_secret(apps, schema_editor):  # pragma: no cover
    User = apps.get_model("users", "User")

    for user in User.objects.filter(email_verification_secret=None):
        user.email_verification_secret = generate_secret(64)
        user.save(update_fields=("email_verification_secret",))


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_user_two_factor_secret"),
    ]

    operations = [
        migrations.RunPython(ensure_email_verification_secret, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="user",
            name="email_verification_secret",
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
