# Generated by Django 5.1.4 on 2025-02-12 22:28

import django.utils.timezone
from django.db import migrations, models

import temba.users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_user_email_verification_secret"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", temba.users.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
