# Generated by Django 5.1.4 on 2025-02-24 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_alter_user_email_alter_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
