# Generated by Django 5.1.4 on 2025-04-25 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_migrate_mfa"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="backuptoken",
            name="user",
        ),
        migrations.DeleteModel(
            name="FailedLogin",
        ),
        migrations.RemoveField(
            model_name="recoverytoken",
            name="user",
        ),
        migrations.DeleteModel(
            name="BackupToken",
        ),
        migrations.DeleteModel(
            name="RecoveryToken",
        ),
    ]
