# Generated by Django 5.1.9 on 2025-05-13 15:42

from django.db import migrations

from temba.utils.uuid import uuid4


def backfill_user_uuid(apps, schema_editor):  # pragma: no cover
    User = apps.get_model("users", "User")

    for user in User.objects.filter(uuid=None):
        user.uuid = uuid4()
        user.save(update_fields=("uuid",))


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_user_uuid"),
    ]

    operations = [
        migrations.RunPython(backfill_user_uuid, migrations.RunPython.noop),
    ]
