# Generated by Django 5.2.2 on 2025-07-02 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_squashed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="last_auth_on",
        ),
    ]
