# Generated by Django 5.1.4 on 2025-02-12 17:00

from django.db import migrations, transaction

from temba.utils.uuid import uuid4


def populate_channel_events_uuid(apps, schema_editor):  # pragma: no cover
    ChannelEvent = apps.get_model("channels", "ChannelEvent")

    num_updated = 0
    while True:
        batch = list(ChannelEvent.objects.filter(uuid=None)[:1000])
        if not batch:
            return

        with transaction.atomic():
            for event in batch:
                event.uuid = uuid4()
                event.save(update_fields=("uuid",))

        num_updated += len(batch)
        print(f"Updated {num_updated} channel events")


def apply_manual():  # pragma: no cover
    from django.apps import apps

    populate_channel_events_uuid(apps, None)


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0189_channelevent_uuid_alter_channelevent_event_type"),
    ]

    operations = [
        migrations.RunPython(populate_channel_events_uuid, migrations.RunPython.noop),
    ]
