# Generated by Django 5.1.4 on 2025-02-14 21:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0190_populate_channelevents_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="syncevent",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="syncevent",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="syncevent",
            name="modified_by",
        ),
        migrations.RemoveField(
            model_name="syncevent",
            name="modified_on",
        ),
        migrations.AlterField(
            model_name="syncevent",
            name="created_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
