# Generated by Django 5.1.4 on 2025-02-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0192_alter_channelevent_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="is_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
