# Generated by Django 5.1.4 on 2025-04-02 16:04

from django.db import migrations


def populate_max_concurrent_calls(apps, schema_editor):  # pragma: no cover
    Channel = apps.get_model("channels", "Channel")

    channels = Channel.objects.filter(config__max_concurrent_events__isnull=False)
    num_updated = 0
    for channel in channels:
        value = channel.config.pop("max_concurrent_events")
        if value is not None:
            channel.config["max_concurrent_calls"] = int(value)
        channel.save(update_fields=("config",))
        num_updated += 1

    if num_updated:
        print(f"Updated {num_updated} channels")


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0193_channel_is_enabled"),
    ]

    operations = [
        migrations.RunPython(populate_max_concurrent_calls, migrations.RunPython.noop),
    ]
