# Generated by Django 5.2.1 on 2025-05-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0195_migrate_bandwidth_app_ids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="syncevent",
            name="lifetime",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="syncevent",
            name="power_status",
            field=models.CharField(
                choices=[
                    ("UNK", "Unknown"),
                    ("CHA", "Charging"),
                    ("DIS", "Discharging"),
                    ("NOT", "Not Charging"),
                    ("FUL", "Full"),
                ],
                default="UNK",
                max_length=64,
            ),
        ),
    ]
