# Generated by Django 5.2.1 on 2025-05-29 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0196_alter_syncevent_lifetime_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="syncevent",
            name="lifetime",
        ),
    ]
