# Generated by Django 5.2.1 on 2025-06-03 18:53

from django.db import migrations, models

SQL = """
DROP TRIGGER temba_channellog_update_channelcount ON channels_channellog;
DROP FUNCTION temba_update_channellog_count();
"""


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0197_remove_syncevent_lifetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channelcount",
            name="count_type",
            field=models.CharField(
                choices=[
                    ("IM", "Incoming Message"),
                    ("OM", "Outgoing Message"),
                    ("IV", "Incoming Voice"),
                    ("OV", "Outgoing Voice"),
                ],
                max_length=2,
            ),
        ),
        migrations.RunSQL(SQL),
    ]
