# Generated by Django 5.2.1 on 2025-06-03 20:46

from django.db import migrations


def cleanup_counts(apps, schema_editor):  # pragma: no cover
    ChannelCount = apps.get_model("channels", "ChannelCount")

    num_deleted, _ = ChannelCount.objects.exclude(count_type__in=("IM", "OM", "IV", "OV")).delete()
    if num_deleted:
        print(f"Deleted {num_deleted} ChannelCount records with unsupported count_type.")


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0198_alter_channelcount_count_type"),
    ]

    operations = [
        migrations.RunPython(cleanup_counts, migrations.RunPython.noop),
    ]
