# Generated by Django 5.2.1 on 2025-06-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0201_backfill_channelcount_scope"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="channelcount",
            name="channels_ch_channel_cf3039_idx",
        ),
        migrations.AlterField(
            model_name="channelcount",
            name="count_type",
            field=models.CharField(null=True),
        ),
    ]
