# Generated by Django 5.2.1 on 2025-06-04 19:42

from django.db import migrations

SQL = """
----------------------------------------------------------------------
-- Handles INSERT statements on msg table
----------------------------------------------------------------------
CREATE OR REPLACE FUNCTION temba_msg_on_insert() RETURNS TRIGGER AS $$
BEGIN
    -- add broadcast counts for all new broadcast values
    INSERT INTO msgs_broadcastmsgcount("broadcast_id", "count", "is_squashed")
    SELECT broadcast_id, count(*), FALSE FROM newtab WHERE broadcast_id IS NOT NULL GROUP BY broadcast_id;

    -- add positive item counts for all rows which belong to a folder
    INSERT INTO orgs_itemcount("org_id", "scope", "count", "is_squashed")
    SELECT org_id, temba_msg_countscope(newtab), count(*), FALSE FROM newtab
    WHERE temba_msg_countscope(newtab) IS NOT NULL
    GROUP BY 1, 2;

    -- add channel counts for all messages with a channel
    INSERT INTO channels_channelcount("channel_id", "scope", "day", "count", "is_squashed")
    SELECT channel_id, temba_msg_channel_countscope(newtab), created_on::date, count(*), FALSE FROM newtab
    WHERE channel_id IS NOT NULL GROUP BY channel_id, temba_msg_channel_countscope(newtab), created_on::date;

    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP FUNCTION temba_msg_determine_channel_count_code(msgs_msg);
"""


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0202_remove_channelcount_channels_ch_channel_cf3039_idx_and_more"),
    ]

    operations = [
        migrations.RunSQL(SQL),
    ]
