# Generated by Django 5.2.1 on 2025-06-04 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0203_update_count_triggers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="channelcount",
            name="count_type",
        ),
        migrations.AlterField(
            model_name="channelcount",
            name="channel",
            field=models.ForeignKey(
                db_index=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="counts",
                to="channels.channel",
            ),
        ),
        migrations.AlterField(
            model_name="channelcount",
            name="scope",
            field=models.CharField(max_length=128),
        ),
    ]
