# Generated by Django 5.2.2 on 2025-06-19 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0204_remove_channelcount_count_type_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChannelLog",
        ),
    ]
