# Generated by Django 5.2.2 on 2025-07-02 14:48

import django_countries.fields

import django.contrib.postgres.fields
import django.utils.timezone
from django.db import migrations, models

import temba.channels.models
import temba.orgs.models
import temba.utils.models.base
import temba.utils.models.fields
import temba.utils.uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this item is active, use this instead of deleting",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this item was originally created",
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this item was last modified",
                    ),
                ),
                (
                    "uuid",
                    models.CharField(
                        db_index=True,
                        default=temba.utils.models.base.generate_uuid,
                        help_text="The unique identifier for this object",
                        max_length=36,
                        unique=True,
                        verbose_name="Unique Identifier",
                    ),
                ),
                ("is_system", models.BooleanField(default=False)),
                ("channel_type", models.CharField(max_length=3)),
                ("name", models.CharField(max_length=64)),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        help_text="Address with which this channel communicates",
                        max_length=255,
                        null=True,
                        verbose_name="Address",
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        blank=True,
                        help_text="Country which this channel is for",
                        max_length=2,
                        null=True,
                        verbose_name="Country",
                    ),
                ),
                ("config", models.JSONField(default=dict)),
                (
                    "schemes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=16),
                        default=temba.channels.models._get_default_channel_scheme,
                        size=None,
                    ),
                ),
                ("role", models.CharField(default="SR", max_length=4)),
                (
                    "log_policy",
                    models.CharField(
                        choices=[
                            ("N", "Discard All"),
                            ("E", "Write Errors Only"),
                            ("A", "Write All"),
                        ],
                        default="A",
                        max_length=1,
                    ),
                ),
                ("tps", models.IntegerField(null=True)),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "claim_code",
                    models.CharField(blank=True, max_length=16, null=True, unique=True),
                ),
                (
                    "secret",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("device", models.CharField(blank=True, max_length=255, null=True)),
                ("os", models.CharField(blank=True, max_length=255, null=True)),
                ("last_seen", models.DateTimeField(null=True)),
            ],
            options={
                "ordering": ("-last_seen", "-pk"),
            },
            bases=(models.Model, temba.orgs.models.DependencyMixin),
        ),
        migrations.CreateModel(
            name="ChannelCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
                ),
                ("count", models.IntegerField()),
                ("is_squashed", models.BooleanField(default=False)),
                ("scope", models.CharField(max_length=128)),
                ("day", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="ChannelEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=temba.utils.uuid.uuid4, unique=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("mt_call", "Outgoing Call"),
                            ("mt_miss", "Missed Outgoing Call"),
                            ("mo_call", "Incoming Call"),
                            ("mo_miss", "Missed Incoming Call"),
                            ("stop_contact", "Stop Contact"),
                            ("new_conversation", "New Conversation"),
                            ("referral", "Referral"),
                            ("welcome_message", "Welcome Message"),
                            ("optin", "Opt In"),
                            ("optout", "Opt Out"),
                            ("delete_contact", "Delete Contact"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("P", "Pending"), ("H", "Handled")],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "extra",
                    temba.utils.models.fields.JSONAsTextField(default=dict, null=True),
                ),
                ("occurred_on", models.DateTimeField()),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "log_uuids",
                    django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), null=True, size=None),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SyncEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "power_source",
                    models.CharField(
                        choices=[
                            ("AC", "A/C"),
                            ("USB", "USB"),
                            ("WIR", "Wireless"),
                            ("BAT", "Battery"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "power_status",
                    models.CharField(
                        choices=[
                            ("UNK", "Unknown"),
                            ("CHA", "Charging"),
                            ("DIS", "Discharging"),
                            ("NOT", "Not Charging"),
                            ("FUL", "Full"),
                        ],
                        default="UNK",
                        max_length=64,
                    ),
                ),
                ("power_level", models.IntegerField()),
                ("network_type", models.CharField(max_length=128)),
                ("pending_message_count", models.IntegerField(default=0)),
                ("retry_message_count", models.IntegerField(default=0)),
                ("incoming_command_count", models.IntegerField(default=0)),
                ("outgoing_command_count", models.IntegerField(default=0)),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
