# Generated by Django 5.2.6 on 2025-10-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0208_backfill_channel_events"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channelcount",
            name="count",
            field=models.BigIntegerField(),
        ),
    ]
