# Generated by Django 5.1.4 on 2025-01-13 18:20

from django.db import migrations


def backfill_msg_is_android(apps, schema_editor):  # pragma: no cover
    Msg = apps.get_model("msgs", "Msg")

    num_updated = 0
    while True:
        batch = list(Msg.objects.filter(is_android=None).select_related("channel")[:1000])
        if not batch:
            return

        for msg in batch:
            msg.is_android = bool(msg.channel and msg.channel.channel_type == "A")
            msg.save(update_fields=("is_android",))

        num_updated += len(batch)

        print(f"Updated {num_updated} messages")


class Migration(migrations.Migration):

    dependencies = [("msgs", "0282_squashed")]

    operations = [migrations.RunPython(backfill_msg_is_android, migrations.RunPython.noop)]
