# Generated by Django 5.1.4 on 2025-01-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0283_backfill_msg_is_android"),
    ]

    operations = [
        migrations.AlterField(
            model_name="msg",
            name="is_android",
            field=models.BooleanField(),
        ),
    ]
