# Generated by Django 5.1.4 on 2025-01-13 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0284_alter_msg_is_android"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SystemLabelCount",
        ),
    ]
