# Generated by Django 5.1.4 on 2025-03-21 15:34

from django.db import migrations


def update_quick_replies(apps, schema_editor):  # pragma: no cover
    Broadcast = apps.get_model("msgs", "Broadcast")

    num_updated = 0

    for broadcast in Broadcast.objects.filter(is_active=True).only("translations"):
        updated = False
        for trans in broadcast.translations.values():
            if "quick_replies" in trans:
                for i, qr in enumerate(trans["quick_replies"]):
                    if isinstance(qr, str):
                        trans["quick_replies"][i] = {"text": qr}
                        updated = True
        if updated:
            broadcast.save(update_fields=("translations",))
            num_updated += 1

            print(f"Updated {num_updated} broadcasts with quick replies")


def apply_manual():  # pragma: no cover
    from django.apps import apps

    update_quick_replies(apps, None)


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0285_delete_systemlabelcount"),
    ]

    operations = [
        migrations.RunPython(update_quick_replies, migrations.RunPython.noop),
    ]
