# Generated by Django 5.1.9 on 2025-05-26 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0286_update_quick_replies"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="msg",
            name="metadata",
        ),
    ]
