# Generated by Django 5.2.2 on 2025-09-23 16:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0208_backfill_channel_events"),
        ("contacts", "0210_clear_deps_for_deleted_groups"),
        ("flows", "0396_remove_flowrun_path_alter_flowrun_session_uuid"),
        ("msgs", "0289_squashed"),
        ("orgs", "0172_squashed"),
        ("tickets", "0086_backfill_ticket_events"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="msg",
            name="msgs_inbox",
        ),
        migrations.RemoveIndex(
            model_name="msg",
            name="msgs_flows",
        ),
        migrations.RemoveIndex(
            model_name="msg",
            name="msgs_archived",
        ),
        migrations.AddIndex(
            model_name="msg",
            index=models.Index(
                condition=models.Q(("direction", "I"), ("flow__isnull", True), ("status", "H"), ("visibility", "V")),
                fields=["org", "-created_on", "-id"],
                name="msgs_inbox",
            ),
        ),
        migrations.AddIndex(
            model_name="msg",
            index=models.Index(
                condition=models.Q(("direction", "I"), ("flow__isnull", False), ("status", "H"), ("visibility", "V")),
                fields=["org", "-created_on", "-id"],
                name="msgs_flows",
            ),
        ),
        migrations.AddIndex(
            model_name="msg",
            index=models.Index(
                condition=models.Q(("direction", "I"), ("status", "H"), ("visibility", "A")),
                fields=["org", "-created_on", "-id"],
                name="msgs_archived",
            ),
        ),
    ]
