# Generated by Django 5.2.2 on 2025-09-23 18:54

from django.db import migrations

SQL = """
----------------------------------------------------------------------
-- Determines the item count scope for a msg record
----------------------------------------------------------------------
CREATE OR REPLACE FUNCTION temba_msg_countscope(_msg msgs_msg) RETURNS TEXT STABLE AS $$
BEGIN
  IF _msg.direction = 'I' THEN
    IF _msg.visibility = 'V' AND _msg.status = 'H' AND _msg.flow_id IS NULL THEN
      RETURN 'msgs:folder:I';
    ELSIF _msg.visibility = 'V' AND _msg.status = 'H' AND _msg.flow_id IS NOT NULL THEN
      RETURN 'msgs:folder:W';
    ELSIF _msg.visibility = 'A'  AND _msg.status = 'H' THEN
      RETURN 'msgs:folder:A';
    END IF;
  ELSE
    IF _msg.VISIBILITY = 'V' THEN
      IF _msg.status = 'I' OR _msg.status = 'Q' OR _msg.status = 'E' THEN
        RETURN 'msgs:folder:O';
      ELSIF _msg.status = 'W' OR _msg.status = 'S' OR _msg.status = 'D' OR _msg.status = 'R' THEN
        RETURN 'msgs:folder:S';
      ELSIF _msg.status = 'F' THEN
        RETURN 'msgs:folder:X';
      END IF;
    END IF;
  END IF;

  RETURN NULL;
END;
$$ LANGUAGE plpgsql;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0290_remove_msg_msgs_inbox_remove_msg_msgs_flows_and_more"),
        ("sql", "0008_squashed"),
    ]

    operations = [
        migrations.RunSQL(SQL),
    ]
