# Generated by Django 5.2.2 on 2025-09-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0292_fix_folder_counts"),
    ]

    operations = [
        migrations.AddField(
            model_name="broadcast",
            name="uuid",
            field=models.UUIDField(null=True),
        ),
    ]
