# Generated by Django 5.2.2 on 2025-09-24 19:03

from django.db import migrations

from temba.utils.uuid import uuid7


def backfill_broadcast_uuids(apps, schema_editor):
    Broadcast = apps.get_model("msgs", "Broadcast")

    num_updated = 0

    while True:
        batch = list(Broadcast.objects.filter(uuid__isnull=True).only("uuid", "created_on")[:1000])
        if not batch:
            break

        for bcast in batch:
            bcast.uuid = uuid7(bcast.created_on)
            num_updated += 1

        Broadcast.objects.bulk_update(batch, ["uuid"])
        print(f"Updated {num_updated} broadcasts with new UUIDs")


def apply_manual():  # pragma: no cover
    from django.apps import apps

    backfill_broadcast_uuids(apps, None)


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0293_broadcast_uuid"),
    ]

    operations = [
        migrations.RunPython(backfill_broadcast_uuids, migrations.RunPython.noop),
    ]
