# Generated by Django 5.2.2 on 2025-09-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0294_backfill_bcast_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="msg",
            name="ticket_uuid",
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name="broadcast",
            name="uuid",
            field=models.UUIDField(unique=True),
        ),
    ]
