# Generated by Django 5.2.2 on 2025-09-26 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0295_msg_ticket_uuid_alter_broadcast_uuid"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="msg",
            name="msgs_api_incoming",
        ),
    ]
