# Generated by Django 5.2.2 on 2025-09-26 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0296_remove_msg_msgs_api_incoming"),
    ]

    operations = [
        migrations.AlterField(
            model_name="msg",
            name="created_on",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="msg",
            name="status",
            field=models.CharField(
                choices=[
                    ("P", "Pending"),
                    ("H", "Handled"),
                    ("I", "Initializing"),
                    ("Q", "Queued"),
                    ("W", "Wired"),
                    ("S", "Sent"),
                    ("D", "Delivered"),
                    ("R", "Read"),
                    ("E", "Error"),
                    ("F", "Failed"),
                ],
                default="P",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="msg",
            name="uuid",
            field=models.UUIDField(unique=True),
        ),
    ]
