# Generated by Django 5.2.6 on 2025-10-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0297_alter_msg_created_on_alter_msg_status_alter_msg_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="broadcastmsgcount",
            name="count",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="labelcount",
            name="count",
            field=models.BigIntegerField(),
        ),
    ]
