# Generated by Django 5.2.8 on 2025-11-10 22:07

from django.db import migrations
from django.db.models import Prefetch

from temba.utils import dynamo

STATUS_WIRED = "W"
STATUS_SENT = "S"
STATUS_DELIVERED = "D"
STATUS_READ = "R"
STATUS_ERRORED = "E"
STATUS_FAILED = "F"

status_to_tag = {
    STATUS_WIRED: "wired",
    STATUS_SENT: "sent",
    STATUS_DELIVERED: "delivered",
    STATUS_READ: "read",
    STATUS_ERRORED: "errored",
    STATUS_FAILED: "failed",
}

FAILED_NO_DESTINATION = "D"
FAILED_CONTACT = "C"
FAILED_SUSPENDED = "S"
FAILED_LOOPING = "L"
FAILED_ERROR_LIMIT = "E"
FAILED_TOO_OLD = "O"
FAILED_CHANNEL_REMOVED = "R"

# Msg.failed_reason codes that are stored on events as "unsendable_reason"
failed_reason_to_unsendable = {
    FAILED_NO_DESTINATION: "no_route",
    FAILED_CONTACT: "contact_blocked",
    FAILED_SUSPENDED: "org_suspended",
    FAILED_LOOPING: "looping",
}

# Msg.failed_reason codes that are stored as "reason" on status tags
failed_reason_to_tag_reason = {
    FAILED_ERROR_LIMIT: "error_limit",
    FAILED_TOO_OLD: "too_old",
    FAILED_CHANNEL_REMOVED: "channel_removed",
}

VISIBILITY_DELETED_BY_USER = "D"
VISIBILITY_DELETED_BY_SENDER = "X"


def backfill_msg_events(apps, schema_editor):
    Msg = apps.get_model("msgs", "Msg")
    Contact = apps.get_model("contacts", "Contact")

    msgs = Msg.objects.filter(org__is_active=True, contact__is_active=True).prefetch_related(
        Prefetch("contact", Contact.objects.only("uuid")),
    )

    before_id = None
    num_written = 0

    while True:
        batch = msgs.order_by("-id")
        if before_id:
            batch = batch.filter(id__lt=before_id)

        batch = list(batch[:100])
        if not batch:
            break

        try:
            with dynamo.HISTORY.batch_writer() as writer:
                for msg in batch:
                    if msg.direction == "I":
                        writer.put_item(
                            {
                                "PK": f"con#{msg.contact.uuid}",
                                "SK": f"evt#{msg.uuid}",
                                "OrgID": msg.org_id,
                                "Data": {
                                    "type": "msg_received",
                                    "created_on": msg.created_on.isoformat(),
                                    "msg": _msg_in(msg),
                                },
                            }
                        )

                        if msg.visibility == VISIBILITY_DELETED_BY_SENDER:
                            writer.put_item(
                                {
                                    "PK": f"con#{msg.contact.uuid}",
                                    "SK": f"evt#{msg.uuid}#del",
                                    "OrgID": msg.org_id,
                                    "Data": {
                                        "created_on": msg.modified_on.isoformat(),
                                        "by_contact": True,
                                    },
                                }
                            )
                        elif msg.visibility == VISIBILITY_DELETED_BY_USER:
                            writer.put_item(
                                {
                                    "PK": f"con#{msg.contact.uuid}",
                                    "SK": f"evt#{msg.uuid}#del",
                                    "OrgID": msg.org_id,
                                    "Data": {
                                        "created_on": msg.modified_on.isoformat(),
                                    },
                                }
                            )
                    else:
                        if msg.msg_type == "V":
                            writer.put_item(
                                {
                                    "PK": f"con#{msg.contact.uuid}",
                                    "SK": f"evt#{msg.uuid}",
                                    "OrgID": msg.org_id,
                                    "Data": {
                                        "type": "ivr_created",
                                        "created_on": msg.created_on.isoformat(),
                                        "msg": _msg_out(msg),
                                    },
                                }
                            )
                        else:
                            writer.put_item(
                                {
                                    "PK": f"con#{msg.contact.uuid}",
                                    "SK": f"evt#{msg.uuid}",
                                    "OrgID": msg.org_id,
                                    "Data": {
                                        "type": "msg_created",
                                        "created_on": msg.created_on.isoformat(),
                                        "msg": _msg_out(msg),
                                    },
                                }
                            )

                            if msg.status in status_to_tag and msg.failed_reason not in failed_reason_to_unsendable:
                                data = {"created_on": msg.modified_on.isoformat(), "status": status_to_tag[msg.status]}
                                if msg.status == STATUS_FAILED and msg.failed_reason in failed_reason_to_tag_reason:
                                    data["reason"] = failed_reason_to_tag_reason[msg.failed_reason]

                                writer.put_item(
                                    {
                                        "PK": f"con#{msg.contact.uuid}",
                                        "SK": f"evt#{msg.uuid}#sts",
                                        "OrgID": msg.org_id,
                                        "Data": data,
                                    }
                                )

                    num_written += 1
                    before_id = msg.id
        except Exception as e:  # pragma: no cover
            print(e)
            print(f"before_id={before_id}")
            break

        last_id, last_created_on = batch[-1].id, batch[-1].created_on

        print(f"Wrote {num_written} msg events (last id={last_id}, created_on={last_created_on.isoformat()})")


def _msg_in(obj) -> dict:
    d = _base_msg(obj)

    if obj.external_id:
        d["external_id"] = obj.external_id

    return d


def _msg_out(obj) -> dict:
    d = _base_msg(obj)

    if obj.quick_replies:
        d["quick_replies"] = obj.quick_replies
    if obj.failed_reason in failed_reason_to_unsendable:
        d["unsendable_reason"] = failed_reason_to_unsendable[obj.failed_reason]

    return d


def _base_msg(obj) -> dict:
    d = {
        "urn": obj.contact_urn.identity if obj.contact_urn else None,
        "channel": _channel(obj.channel) if obj.channel else None,
        "text": obj.text,
    }
    if obj.attachments:
        d["attachments"] = obj.attachments

    return d


def _channel(channel) -> dict:
    return {"uuid": str(channel.uuid), "name": channel.name}


def apply_manual():  # pragma: no cover
    from django.apps import apps

    backfill_msg_events(apps, None)


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0298_alter_broadcastmsgcount_count_alter_labelcount_count"),
    ]

    operations = [
        migrations.RunPython(backfill_msg_events, reverse_code=migrations.RunPython.noop),
    ]
