# Generated by Django 5.1.4 on 2025-02-14 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0013_squashed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="video",
            name="modified_by",
        ),
        migrations.DeleteModel(
            name="Lead",
        ),
        migrations.DeleteModel(
            name="Video",
        ),
    ]
