# Generated by Django 5.1.4 on 2025-01-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contacts", "0197_squashed"),
        ("flows", "0350_squashed"),
        ("globals", "0013_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="flow",
            name="global_dependencies",
            field=models.ManyToManyField(related_name="dependent_flows", to="globals.global"),
        ),
        migrations.AddField(
            model_name="flow",
            name="group_dependencies",
            field=models.ManyToManyField(related_name="dependent_flows", to="contacts.contactgroup"),
        ),
    ]
