# Generated by Django 5.1.4 on 2025-01-06 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("flows", "0351_squashed"),
        ("msgs", "0281_squashed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="flow",
            name="label_dependencies",
            field=models.ManyToManyField(related_name="dependent_flows", to="msgs.label"),
        ),
        migrations.AddField(
            model_name="flow",
            name="modified_by",
            field=models.ForeignKey(
                help_text="The user which last modified this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_modifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="flow",
            name="optin_dependencies",
            field=models.ManyToManyField(related_name="dependent_flows", to="msgs.optin"),
        ),
    ]
