# Generated by Django 5.1.4 on 2025-01-07 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0353_squashed"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlowResultCount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("count", models.IntegerField()),
                ("is_squashed", models.BooleanField(default=False)),
                ("result", models.CharField(max_length=64)),
                ("category", models.CharField(max_length=64)),
                (
                    "flow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="result_counts", to="flows.flow"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        condition=models.Q(("is_squashed", False)),
                        fields=["flow", "result", "category"],
                        name="flowresultcount_unsquashed",
                    )
                ],
            },
        ),
    ]
