# Generated by Django 5.1.4 on 2025-01-13 14:44

from django.db import migrations

SQL = """
DROP TRIGGER temba_flowrun_delete ON flows_flowrun;
DROP TRIGGER temba_flowrun_update_flowcategorycount ON flows_flowrun;

DROP FUNCTION temba_flowrun_delete();
DROP FUNCTION temba_update_flowcategorycount();
DROP FUNCTION temba_update_category_counts(integer, json, json);
DROP FUNCTION temba_insert_flowcategorycount(integer, text, json, integer);
"""


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0355_backfill_new_cat_counts"),
        ("sql", "0007_squashed"),
    ]

    operations = [migrations.RunSQL(SQL)]
