# Generated by Django 5.1.4 on 2025-01-13 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0356_update_triggers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flownodecount",
            name="flow",
        ),
        migrations.RemoveField(
            model_name="flowpathcount",
            name="flow",
        ),
        migrations.RemoveField(
            model_name="flowrunstatuscount",
            name="flow",
        ),
        migrations.DeleteModel(
            name="FlowCategoryCount",
        ),
        migrations.DeleteModel(
            name="FlowNodeCount",
        ),
        migrations.DeleteModel(
            name="FlowPathCount",
        ),
        migrations.DeleteModel(
            name="FlowRunStatusCount",
        ),
    ]
