# Generated by Django 5.1.4 on 2025-01-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0357_remove_flownodecount_flow_remove_flowpathcount_flow_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="flowsession",
            name="modified_on",
            field=models.DateTimeField(null=True),
        ),
    ]
