# Generated by Django 5.1.4 on 2025-01-20 14:29

from django.db import migrations
from django.db.models import F
from django.db.models.functions import Greatest


def backfill_session_modified_on(apps, schema_editor):  # pragma: no cover
    FlowSession = apps.get_model("flows", "FlowSession")

    num_updated = 0

    while True:
        batch_ids = list(FlowSession.objects.filter(modified_on=None).values_list("id", flat=True)[:1000])
        if not batch_ids:
            break

        FlowSession.objects.filter(id__in=batch_ids).update(
            modified_on=Greatest(
                F("created_on"), F("wait_expires_on"), F("wait_started_on"), F("timeout_on"), F("ended_on")
            )
        )
        num_updated += len(batch_ids)

        print(f"Updated {num_updated} sessions")


def apply_manual():  # pragma: no cover
    from django.apps import apps

    backfill_session_modified_on(apps, None)


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0358_flowsession_modified_on"),
    ]

    operations = [migrations.RunPython(backfill_session_modified_on, migrations.RunPython.noop)]
