# Generated by Django 5.1.4 on 2025-01-20 15:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0359_backfill_session_modified_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flowsession",
            name="modified_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
