# Generated by Django 5.1.4 on 2025-01-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0199_contactfire"),
        ("flows", "0360_alter_flowsession_modified_on"),
        ("ivr", "0031_squashed"),
        ("orgs", "0165_grant_prometheus_feature"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="flowsession",
            name="flows_session_waiting_has_started_and_expires",
        ),
        migrations.RemoveIndex(
            model_name="flowsession",
            name="flows_session_message_expires",
        ),
        migrations.RemoveIndex(
            model_name="flowsession",
            name="flows_session_voice_expires",
        ),
        migrations.AddIndex(
            model_name="flowsession",
            index=models.Index(
                condition=models.Q(("status", "W"), ("wait_expires_on__isnull", False)),
                fields=["wait_expires_on"],
                name="flows_session_waiting_expires",
            ),
        ),
    ]
