# Generated by Django 5.1.4 on 2025-01-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0361_remove_flowsession_flows_session_waiting_has_started_and_expires_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flowsession",
            name="wait_resume_on_expire",
            field=models.BooleanField(null=True),
        ),
    ]
