# Generated by Django 5.1.4 on 2025-01-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0362_alter_flowsession_wait_resume_on_expire"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flowsession",
            name="status",
            field=models.CharField(
                choices=[("W", "Waiting"), ("C", "Completed"), ("I", "Interrupted"), ("F", "Failed")], max_length=1
            ),
        ),
    ]
