# Generated by Django 5.1.4 on 2025-01-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0363_alter_flowsession_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="flowsession",
            name="last_sprint_uuid",
            field=models.UUIDField(null=True),
        ),
    ]
