# Generated by Django 5.1.4 on 2025-02-03 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0365_backfill_fires"),
    ]

    operations = [
        migrations.AddField(
            model_name="flowrun",
            name="session_uuid",
            field=models.UUIDField(null=True),
        ),
    ]
