# Generated by Django 5.1.4 on 2025-02-04 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0367_remove_flowsession_flowsessions_timed_out_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flowsession",
            name="modified_on",
        ),
        migrations.RemoveField(
            model_name="flowsession",
            name="responded",
        ),
        migrations.RemoveField(
            model_name="flowsession",
            name="timeout_on",
        ),
        migrations.RemoveField(
            model_name="flowsession",
            name="wait_expires_on",
        ),
        migrations.RemoveField(
            model_name="flowsession",
            name="wait_resume_on_expire",
        ),
        migrations.RemoveField(
            model_name="flowsession",
            name="wait_started_on",
        ),
    ]
