# Generated by Django 5.1.4 on 2025-02-17 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0370_remove_flowrun_delete_from_results"),
        ("orgs", "0169_delete_usersettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flowsession",
            name="org",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name="sessions", to="orgs.org"
            ),
        ),
    ]
