# Generated by Django 5.1.4 on 2025-02-17 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0371_alter_flowsession_org"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flowsession",
            name="org",
        ),
    ]
