# Generated by Django 5.1.4 on 2025-02-19 15:54

from django.db import migrations

MAX_EXPIRES_AFTER = 60 * 24 * 14  # 2 weeks


def fix_expires_after(apps, schema_editor):  # pragma: no cover
    Flow = apps.get_model("flows", "Flow")

    num_updated = Flow.objects.filter(expires_after_minutes__gt=MAX_EXPIRES_AFTER).update(
        expires_after_minutes=MAX_EXPIRES_AFTER
    )
    if num_updated:
        print(f"Updated {num_updated} flows with expires_after_minutes > {MAX_EXPIRES_AFTER}")


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0372_remove_flowsession_org"),
    ]

    operations = [
        migrations.RunPython(fix_expires_after, migrations.RunPython.noop),
    ]
