# Generated by Django 5.1.4 on 2025-02-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0374_backfill_run_session_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flow",
            name="expires_after_minutes",
            field=models.IntegerField(
                default=4320, help_text="Minutes of inactivity that will cause expiration from flow."
            ),
        ),
    ]
