# Generated by Django 5.1.4 on 2025-02-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0202_backfill_current_session_uuid"),
        ("flows", "0375_alter_flow_expires_after_minutes"),
        ("orgs", "0169_delete_usersettings"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="flowrun",
            index=models.Index(
                condition=models.Q(("status__in", ("A", "W"))), fields=["session_uuid"], name="flowruns_by_session"
            ),
        ),
    ]
