# Generated by Django 5.1.4 on 2025-02-26 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0378_alter_flowrun_session_alter_flowsession_status"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="flowrun",
            name="flows_run_active_or_waiting_has_session",
        ),
    ]
