# Generated by Django 5.1.4 on 2025-02-26 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0379_remove_flowrun_flows_run_active_or_waiting_has_session"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flowrun",
            name="session",
        ),
    ]
