# Generated by Django 5.1.4 on 2025-03-05 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0380_remove_flowrun_session"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flowstart",
            name="campaign_event",
        ),
    ]
