# Generated by Django 5.1.4 on 2025-03-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_initial"),
        ("flows", "0381_remove_flowstart_campaign_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="flow",
            name="llm_dependencies",
            field=models.ManyToManyField(related_name="dependent_flows", to="ai.llm"),
        ),
    ]
