# Generated by Django 5.1.4 on 2025-04-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0382_flow_llm_dependencies"),
    ]

    operations = [
        migrations.AddField(
            model_name="flow",
            name="info",
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name="flow",
            name="ivr_retry",
            field=models.IntegerField(null=True),
        ),
    ]
