# Generated by Django 5.1.4 on 2025-04-22 21:08

from django.db import migrations


def backfill_ivr_retry(apps, schema_editor):  # pragma: no cover
    Flow = apps.get_model("flows", "Flow")

    num_updated = 0

    for flow in Flow.objects.filter(flow_type="V", ivr_retry=None).exclude(metadata=None):
        if "ivr_retry" in flow.metadata:
            flow.ivr_retry = flow.metadata["ivr_retry"]
            flow.save(update_fields=["ivr_retry"])
            num_updated += 1

    if num_updated:
        print(f"Backfilled ivr_retry for {num_updated} flows.")


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0383_flow_info_ivr_retrry"),
    ]

    operations = [
        migrations.RunPython(backfill_ivr_retry, migrations.RunPython.noop),
    ]
