# Generated by Django 5.1.4 on 2025-04-23 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0384_backfill_ivr_retry"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flow",
            name="metadata",
        ),
    ]
