# Generated by Django 5.1.9 on 2025-05-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0385_remove_flow_metadata"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flowstart",
            name="calls",
        ),
        migrations.RemoveField(
            model_name="flowstart",
            name="parent_summary",
        ),
        migrations.RemoveField(
            model_name="flowstart",
            name="session_history",
        ),
        migrations.AlterField(
            model_name="flowstart",
            name="start_type",
            field=models.CharField(
                choices=[("M", "Manual"), ("A", "API"), ("Z", "Zapier"), ("T", "Trigger")], max_length=1
            ),
        ),
    ]
