# Generated by Django 5.2.2 on 2025-08-07 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0210_clear_deps_for_deleted_groups"),
        ("flows", "0388_squashed"),
        ("ivr", "0036_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="flowsession",
            name="contact_uuid",
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name="flowsession",
            name="call",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="session", to="ivr.call"
            ),
        ),
        migrations.AlterField(
            model_name="flowsession",
            name="contact",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="contacts.contact"),
        ),
        migrations.AlterField(
            model_name="flowsession",
            name="current_flow",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="sessions", to="flows.flow"
            ),
        ),
    ]
