# Generated by Django 5.2.2 on 2025-08-11 16:15

from django.db import migrations
from django.db.models import Prefetch


def backfill_session_contact_uuid(apps, schema_editor):  # pragma: no cover
    Contact = apps.get_model("contacts", "Contact")
    FlowSession = apps.get_model("flows", "FlowSession")

    num_updated = 0

    while True:
        batch = list(
            FlowSession.objects.filter(status="W", contact_uuid__isnull=True).prefetch_related(
                Prefetch("contact", Contact.objects.only("uuid"))
            )[:1000]
        )
        if not batch:
            break

        for session in batch:
            session.contact_uuid = session.contact.uuid

        FlowSession.objects.bulk_update(batch, ["contact_uuid"])

        num_updated += len(batch)
        print(f"Backfilled contact_uuid on {num_updated} sessions")


def apply_manual():  # pragma: no cover
    from django.apps import apps

    backfill_session_contact_uuid(apps, None)


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0389_flowsession_contact_uuid_alter_flowsession_call_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_session_contact_uuid, reverse_code=migrations.RunPython.noop),
    ]
