# Generated by Django 5.2.2 on 2025-08-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0390_backfill_session_contact_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="flowsession",
            name="current_flow_uuid",
            field=models.UUIDField(null=True),
        ),
    ]
