# Generated by Django 5.2.2 on 2025-08-12 19:44

from django.db import migrations
from django.db.models import Prefetch


def backfill_session_flow_uuid(apps, schema_editor):  # pragma: no cover
    Flow = apps.get_model("flows", "Flow")
    FlowSession = apps.get_model("flows", "FlowSession")

    num_updated = 0

    while True:
        batch = list(
            FlowSession.objects.filter(current_flow__isnull=False, current_flow_uuid__isnull=True).prefetch_related(
                Prefetch("current_flow", Flow.objects.only("uuid"))
            )[:1000]
        )
        if not batch:
            break

        for session in batch:
            session.current_flow_uuid = session.current_flow.uuid

        FlowSession.objects.bulk_update(batch, ["current_flow_uuid"])

        num_updated += len(batch)
        print(f"Backfilled current_flow_uuid on {num_updated} sessions")


def apply_manual():  # pragma: no cover
    from django.apps import apps

    backfill_session_flow_uuid(apps, None)


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0391_flowsession_current_flow_uuid"),
    ]

    operations = [
        migrations.RunPython(backfill_session_flow_uuid, reverse_code=migrations.RunPython.noop),
    ]
