# Generated by Django 5.2.2 on 2025-08-12 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0392_backfill_session_flow_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="flowsession",
            name="call_uuid",
            field=models.UUIDField(null=True),
        ),
    ]
