# Generated by Django 5.2.2 on 2025-08-13 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0393_flowsession_call_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flowsession",
            name="call",
        ),
        migrations.RemoveField(
            model_name="flowsession",
            name="contact",
        ),
        migrations.RemoveField(
            model_name="flowsession",
            name="current_flow",
        ),
    ]
