# Generated by Django 5.2.2 on 2025-09-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0395_backfill_run_started_ended_events"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flowrun",
            name="path",
        ),
        migrations.AlterField(
            model_name="flowrun",
            name="session_uuid",
            field=models.UUIDField(),
        ),
    ]
