# Generated by Django 5.2.6 on 2025-10-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flows", "0396_remove_flowrun_path_alter_flowrun_session_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flowactivitycount",
            name="count",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="flowresultcount",
            name="count",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="flowstartcount",
            name="count",
            field=models.BigIntegerField(),
        ),
    ]
