# Generated by Django 5.1.4 on 2025-01-06 21:25

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0031_squashed"),
        ("orgs", "0162_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="boundaryalias",
            name="org",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="orgs.org"),
        ),
        migrations.AddIndex(
            model_name="adminboundary",
            index=models.Index(
                django.db.models.functions.text.Upper("name"),
                name="adminboundaries_by_name",
            ),
        ),
        migrations.AddIndex(
            model_name="boundaryalias",
            index=models.Index(
                django.db.models.functions.text.Upper("name"),
                name="boundaryaliases_by_name",
            ),
        ),
    ]
