# Generated by Django 5.1.4 on 2025-01-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0032_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminboundary",
            name="geometry",
            field=models.JSONField(null=True),
        ),
    ]
