# Generated by Django 5.1.4 on 2025-01-10 14:30

import geojson

from django.conf import settings
from django.db import migrations


def populate_boundary_geometry(apps, schema_editor):  # pragma: no cover
    if not settings.POSTGIS:
        return

    AdminBoundary = apps.get_model("locations", "AdminBoundary")

    boundaries = AdminBoundary.objects.all().order_by("level", "osm_id")
    for boundary in boundaries:
        boundary.geometry = geojson.loads(boundary.simplified_geometry.geojson)
        boundary.save(update_fields=("geometry",))


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0033_adminboundary_geometry"),
    ]

    operations = [migrations.RunPython(populate_boundary_geometry, migrations.RunPython.noop)]
