#!/bin/bash

set -e

run_as_app_user() {
    su $PROJECT_USER -c "$@"
}

if [ ! -z "${BRANDING_FILES}" ]; then
    echo "Cloning branding files..."
    run_as_app_user "git clone -b $BRANDING_BRANCH $BRANDING_FILES $PROJECT_PATH/$BRANDING_SLUG/"
    mv $PROJECT_PATH/$BRANDING_SLUG/$BRANDING_SLUG/ $PROJECT_PATH/static/brands/
fi

echo "Applying database migrations..."
run_as_app_user "python manage.py migrate --noinput"

echo "Collecting static files..."
run_as_app_user "python manage.py collectstatic --noinput"

if [ "${COMPRESS_ENABLED}" = true ]; then
  echo "Compressing static files..."
  run_as_app_user "python manage.py compress --extension=.haml,.html --force"
fi

echo "Starting nginx..."
service nginx start
echo "Done!"

echo "Starting Gunicorn server..."

exec su $PROJECT_USER -c "exec gunicorn temba.wsgi:application \
    --name=$PROJECT \
    --chdir=$PROJECT_PATH \
    --bind=0.0.0.0:8001 \
    --timeout=120 \
    --log-level=info \
    --log-config=$PROJECT_PATH/docker/gunicorn/gunicorn-logging.conf \
    -c $PROJECT_PATH/docker/gunicorn/gunicorn.conf.py"