#!/bin/bash

#set -o errexit
#set -o pipefail
#set -o nounset

if [ ! -z "${BRANDING_FILES}" ]; then
    git clone -b $BRANDING_BRANCH $BRANDING_FILES $PROJECT_PATH/$BRANDING_SLUG/
    mv $PROJECT_PATH/$BRANDING_SLUG/$BRANDING_SLUG/ $PROJECT_PATH/static/brands/
fi

python manage.py collectstatic --noinput

if [ "${COMPRESS_ENABLED}" = true ]; then
    python manage.py compress --extension=.haml,.html --force
fi

echo "Starting server..."

exec gunicorn temba.wsgi:application \
  --name=$PROJECT \
  --chdir=$PROJECT_PATH \
  --bind=0.0.0.0:8001 \
  --timeout=120 \
  --log-level=info \
  --log-config=$PROJECT_PATH/docker/gunicorn/gunicorn-logging.conf \
  -c $PROJECT_PATH/docker/gunicorn/gunicorn.conf.py