# Generated by Django 5.1.4 on 2025-01-06 21:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("channels", "0187_squashed"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("notification_type", models.CharField(max_length=32)),
                ("medium", models.CharField(max_length=2)),
                ("scope", models.CharField(max_length=36)),
                ("is_seen", models.BooleanField(default=False)),
                ("email_address", models.EmailField(max_length=254, null=True)),
                (
                    "email_status",
                    models.CharField(
                        choices=[("P", "Pending"), ("S", "Sent"), ("N", "None")],
                        default="N",
                        max_length=1,
                    ),
                ),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now)),
                ("data", models.JSONField(default=dict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("incident_type", models.CharField(max_length=32)),
                ("scope", models.CharField(max_length=36)),
                ("started_on", models.DateTimeField(default=django.utils.timezone.now)),
                ("ended_on", models.DateTimeField(null=True)),
                (
                    "channel",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incidents",
                        to="channels.channel",
                    ),
                ),
            ],
        ),
    ]
