# Generated by Django 5.1.4 on 2025-04-15 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0031_squashed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="email_status",
            field=models.CharField(
                choices=[("P", "Pending"), ("S", "Sent"), ("N", "None"), ("U", "Unverified")], default="N", max_length=1
            ),
        ),
    ]
