# Generated by Django 5.1.4 on 2025-03-28 19:08

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_initial"),
        ("orgs", "0169_delete_usersettings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="llm",
            constraint=models.UniqueConstraint(
                models.F("org"), django.db.models.functions.text.Lower("name"), name="unique_llm_names"
            ),
        ),
    ]
