# Generated by Django 5.1.4 on 2025-04-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0002_llm_unique_llm_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="llm",
            name="model",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
