# Generated by Django 5.1.4 on 2025-04-08 19:35

from django.db import migrations


def populate_llm_model(apps, schema_editor):  # pragma: no cover
    LLM = apps.get_model("ai", "LLM")

    for llm in LLM.objects.filter(model=None):
        llm.model = llm.config["model"]
        llm.save(update_fields=("model",))


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0003_llm_model"),
    ]

    operations = [
        migrations.RunPython(populate_llm_model, migrations.RunPython.noop),
    ]
