# Generated by Django 5.1.4 on 2025-04-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0004_populate_llm_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llm",
            name="model",
            field=models.CharField(max_length=64),
        ),
    ]
