# Generated by Django 5.1.4 on 2025-01-17 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0198_squashed"),
        ("orgs", "0165_grant_prometheus_feature"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactFire",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                (
                    "fire_type",
                    models.CharField(choices=[("E", "Expiration"), ("T", "Timeout"), ("C", "Campaign")], max_length=1),
                ),
                ("scope", models.CharField(max_length=64)),
                ("extra", models.JSONField(default=dict)),
                (
                    "contact",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fires",
                        to="contacts.contact",
                    ),
                ),
                ("fire_on", models.DateTimeField(db_index=True)),
                ("org", models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, to="orgs.org")),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("contact", "fire_type", "scope"), name="fire_contact_type_scope_unique"
                    )
                ],
            },
        ),
    ]
