# Generated by Django 5.1.4 on 2025-01-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0199_contactfire"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactfire",
            name="session_uuid",
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name="contactfire",
            name="sprint_uuid",
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name="contactfire",
            name="extra",
            field=models.JSONField(null=True),
        ),
    ]
