# Generated by Django 5.1.4 on 2025-02-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0200_contactfire_session_uuid_contactfire_sprint_uuid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="current_session_uuid",
            field=models.UUIDField(null=True),
        ),
    ]
