# Generated by Django 5.1.4 on 2025-02-20 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0202_backfill_current_session_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactfire",
            name="extra",
        ),
    ]
