# Generated by Django 5.1.4 on 2025-02-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0203_remove_contactfire_extra"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactfire",
            name="fire_type",
            field=models.CharField(
                choices=[
                    ("E", "Wait Expiration"),
                    ("T", "Wait Timeout"),
                    ("S", "Session Expiration"),
                    ("C", "Campaign Event"),
                ],
                max_length=1,
            ),
        ),
    ]
