# Generated by Django 5.1.4 on 2025-02-26 16:27

import random
from datetime import timedelta

from django.db import migrations
from django.db.models import Exists, OuterRef


def create_session_expires_fires(apps, schema_editor):  # pragma: no cover
    Contact = apps.get_model("contacts", "Contact")
    ContactFire = apps.get_model("contacts", "ContactFire")
    FlowSession = apps.get_model("flows", "FlowSession")

    num_created, num_skipped = 0, 0

    while True:
        # find contacts with waiting sessions that don't have a corresponding session expiration fire
        batch = list(
            Contact.objects.filter(current_session_uuid__isnull=False)
            .filter(~Exists(ContactFire.objects.filter(contact=OuterRef("pk"), fire_type="S")))
            .only("id", "org_id", "current_session_uuid")[:1000]
        )
        if not batch:
            break

        sessions = FlowSession.objects.filter(uuid__in=[c.current_session_uuid for c in batch], status="W").only(
            "uuid", "created_on"
        )
        created_on_by_uuid = {s.uuid: s.created_on for s in sessions}

        to_create = []
        for contact in batch:
            session_created_on = created_on_by_uuid.get(contact.current_session_uuid)
            if session_created_on:
                to_create.append(
                    ContactFire(
                        org_id=contact.org_id,
                        contact=contact,
                        fire_type="S",
                        scope="",
                        fire_on=session_created_on + timedelta(days=30) + timedelta(seconds=random.randint(0, 86400)),
                        session_uuid=contact.current_session_uuid,
                    )
                )
            else:
                contact.current_session_uuid = None
                contact.current_flow = None
                contact.save(update_fields=("current_session_uuid", "current_flow"))

                num_skipped += 1

        if to_create:
            ContactFire.objects.bulk_create(to_create)
        num_created += len(to_create)
        print(f"Created {num_created} session expiration fires ({num_skipped} skipped)")


def apply_manual():  # pragma: no cover
    from django.apps import apps

    create_session_expires_fires(apps, None)


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0204_alter_contactfire_fire_type"),
    ]

    operations = [
        migrations.RunPython(create_session_expires_fires, migrations.RunPython.noop),
    ]
