# Generated by Django 5.1.4 on 2025-03-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0205_create_session_expires_fires"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactgroup",
            name="query",
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
