# Generated by Django 5.2.2 on 2025-07-24 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0208_squashed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactgroup",
            name="status",
            field=models.CharField(
                choices=[("I", "Initializing"), ("V", "Evaluating"), ("R", "Ready"), ("X", "Invalid")],
                default="I",
                max_length=1,
            ),
        ),
    ]
