# Generated by Django 5.2.2 on 2025-07-24 21:13

from django.db import migrations


def clear_deps_for_deleted_groups(apps, schema_editor):  # pragma: no cover
    ContactGroup = apps.get_model("contacts", "ContactGroup")

    for group in ContactGroup.objects.filter(is_active=False, group_type="Q").exclude(query_fields=None):
        group.query_fields.clear()


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0209_alter_contactgroup_status"),
    ]

    operations = [
        migrations.RunPython(clear_deps_for_deleted_groups, migrations.RunPython.noop),
    ]
