# Generated by Django 5.2.6 on 2025-10-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0210_clear_deps_for_deleted_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactgroupcount",
            name="count",
            field=models.BigIntegerField(),
        ),
    ]
