# Generated by Django 5.2.9 on 2025-12-18 15:29

from django.db import migrations, models

import temba.utils.uuid


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0211_alter_contactgroupcount_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactimport",
            name="uuid",
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name="contactimport",
            name="uuid",
            field=models.UUIDField(default=temba.utils.uuid.uuid4, null=True),
        ),
    ]
