# Generated by Django 5.2.9 on 2025-12-18 16:41

from django.db import migrations, models

import temba.utils.uuid


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0213_backfill_import_uuids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactimport",
            name="uuid",
            field=models.UUIDField(default=temba.utils.uuid.uuid4, unique=True),
        ),
    ]
