# Generated by Django 4.0.8 on 2026-05-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("request_logs", "0015_squashed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="httplog",
            name="log_type",
            field=models.CharField(
                choices=[
                    ("webhook_called", "Webhook Called"),
                    ("intents_synced", "Intents Synced"),
                    ("classifier_called", "Classifier Called"),
                    ("ticketer_called", "Ticketing Service Called"),
                    ("airtime_transferred", "Airtime Transferred"),
                    ("whatsapp_templates_synced", "WhatsApp Templates Synced"),
                    ("whatsapp_tokens_synced", "WhatsApp Tokens Synced"),
                    ("whatsapp_contacts_refreshed", "WhatsApp Contacts Refreshed"),
                    ("whataspp_check_health", "WhatsApp Health Check"),
                    ("teams_tokens_synced", "Teams Tokens Synced"),
                ],
                max_length=32,
            ),
        ),
    ]
