# Generated by Django 5.2.2 on 2026-09-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("request_logs", "0020_remove_httplog_request_log_classif_8a1320_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="httplog",
            name="log_type",
            field=models.CharField(
                choices=[
                    ("webhook_called", "Webhook Called"),
                    ("airtime_transferred", "Airtime Transferred"),
                    ("whatsapp_templates_synced", "WhatsApp Templates Synced"),
                    ("whatsapp_tokens_synced", "WhatsApp Tokens Synced"),
                    ("whatsapp_contacts_refreshed", "WhatsApp Contacts Refreshed"),
                    ("whataspp_check_health", "WhatsApp Health Check"),
                    ("teams_tokens_synced", "Teams Tokens Synced"),
                ],
                max_length=32,
            ),
        ),
    ]
