# Generated by Django 5.1.4 on 2025-04-21 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0075_backfill_new_daily_counts"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TicketDailyCount",
        ),
        migrations.DeleteModel(
            name="TicketDailyTiming",
        ),
    ]
