# Generated by Django 5.1.4 on 2025-04-23 19:04

from django.db import migrations


def update_opened_counts_scope(apps, schema_editor):
    DailyCount = apps.get_model("orgs", "DailyCount")

    # add zero meaning unknown topic
    DailyCount.objects.filter(scope="tickets:opened").update(scope="tickets:opened:0")


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0076_delete_ticketdailycount_delete_ticketdailytiming"),
    ]

    operations = [
        migrations.RunPython(update_opened_counts_scope, migrations.RunPython.noop),
    ]
