# Generated by Django 5.2.2 on 2025-08-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0079_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketevent",
            name="uuid",
            field=models.UUIDField(null=True),
        ),
    ]
