# Generated by Django 5.2.2 on 2025-08-25 16:19

from django.db import migrations

from temba.utils.uuid import uuid7


def backfill_ticket_event_uuid(apps, schema_editor):  # pragma: no cover
    TicketEvent = apps.get_model("tickets", "TicketEvent")

    num_updated = 0

    while True:
        batch = list(TicketEvent.objects.filter(uuid__isnull=True)[:500])
        if not batch:
            break

        for event in batch:
            event.uuid = uuid7(event.created_on)
        TicketEvent.objects.bulk_update(batch, ["uuid"])

        num_updated += len(batch)
        print(f"Backfilled uuid on {num_updated} ticket events")


def apply_manual():  # pragma: no cover
    from django.apps import apps

    backfill_ticket_event_uuid(apps, None)


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0080_ticketevent_uuid"),
    ]

    operations = [
        migrations.RunPython(backfill_ticket_event_uuid, reverse_code=migrations.RunPython.noop),
    ]
