# Generated by Django 5.2.2 on 2025-08-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0081_backfill_ticket_event_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketevent",
            name="uuid",
            field=models.UUIDField(unique=True),
        ),
    ]
