# Generated by Django 5.2.2 on 2025-08-25 20:35

from itertools import batched

from django.db import migrations

from temba.utils.uuid import is_uuid7, uuid7


def update_ticket_uuids(apps, schema_editor):  # pragma: no cover
    Ticket = apps.get_model("tickets", "Ticket")

    num_updated = 0

    for batch in batched(Ticket.objects.extra(where={"uuid::text not like '019%%'"}).order_by("id"), 100):
        updated = []
        for ticket in batch:
            if not is_uuid7(ticket.uuid):
                ticket.uuid = uuid7(ticket.opened_on)
                updated.append(ticket)
                num_updated += 1

        if updated:
            Ticket.objects.bulk_update(updated, ["uuid"])
            print(f"Updated {num_updated} tickets with new v7 UUIDs")


def apply_manual():  # pragma: no cover
    from django.apps import apps

    update_ticket_uuids(apps, None)


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0082_alter_ticketevent_uuid"),
    ]

    operations = [
        migrations.RunPython(update_ticket_uuids, reverse_code=migrations.RunPython.noop),
    ]
