# Generated by Django 5.2.2 on 2025-08-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0083_update_ticket_uuids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="uuid",
            field=models.UUIDField(unique=True),
        ),
    ]
