# Generated by Django 5.2.2 on 2025-09-09 21:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0210_clear_deps_for_deleted_groups"),
        ("flows", "0395_backfill_run_started_ended_events"),
        ("orgs", "0172_squashed"),
        ("tickets", "0084_alter_ticket_uuid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="ticket",
            name="tickets_contact_open",
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                condition=models.Q(("status", "O")), fields=["contact", "opened_on"], name="tickets_contact_open"
            ),
        ),
    ]
