# Generated by Django 5.2.2 on 2025-09-16 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0086_backfill_ticket_events"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TicketEvent",
        ),
    ]
