# Generated by Django 5.2.2 on 2025-07-02 14:48

from django.db import migrations

from . import InstallSQL


class Migration(migrations.Migration):

    dependencies = [
        ("ivr", "0036_squashed"),
        ("locations", "0037_squashed"),
        ("msgs", "0289_squashed"),
        ("notifications", "0035_squashed"),
        ("orgs", "0172_squashed"),
        ("tickets", "0079_squashed"),
    ]

    operations = [
        InstallSQL("0008_functions"),
        InstallSQL("0008_triggers"),
    ]
