# Generated by Django 5.1.4 on 2025-02-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivr", "0031_squashed"),
    ]

    operations = [
        migrations.AddField(
            model_name="call",
            name="session_uuid",
            field=models.UUIDField(null=True),
        ),
    ]
