# Generated by Django 5.1.9 on 2025-05-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivr", "0032_call_session_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="call",
            name="trigger",
            field=models.JSONField(null=True),
        ),
    ]
