# Generated by Django 5.2.2 on 2025-08-12 22:07

import itertools

from django.db import migrations

from temba.utils.uuid import uuid7


def backfill_call_uuids(apps, schema_editor):  # pragma: no cover
    Call = apps.get_model("ivr", "Call")

    num_updated = 0

    for batch in itertools.batched(Call.objects.filter(uuid__isnull=True).order_by("id"), 100):
        for call in batch:
            call.uuid = uuid7(call.created_on)
            num_updated += 1

        Call.objects.bulk_update(batch, ["uuid"])
        print(f"Updated {num_updated} IVR call records with new v7 UUIDs")


def apply_manual():  # pragma: no cover
    from django.apps import apps

    backfill_call_uuids(apps, None)


class Migration(migrations.Migration):

    dependencies = [
        ("ivr", "0036_squashed"),
    ]

    operations = [
        migrations.RunPython(backfill_call_uuids, migrations.RunPython.noop),
    ]
