# Generated by Django 5.2.2 on 2025-08-12 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ivr", "0037_backfill_call_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="call",
            name="uuid",
            field=models.UUIDField(unique=True),
        ),
    ]
