# Generated by Django 5.2.2 on 2025-07-02 14:48

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("channels", "0206_squashed"),
        ("contacts", "0207_squashed"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trigger",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this item is active, use this instead of deleting",
                    ),
                ),
                (
                    "created_on",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this item was originally created",
                    ),
                ),
                (
                    "modified_on",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this item was last modified",
                    ),
                ),
                ("trigger_type", models.CharField(default="K", max_length=1)),
                ("is_archived", models.BooleanField(default=False)),
                ("priority", models.IntegerField()),
                (
                    "keywords",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=16), null=True, size=None
                    ),
                ),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("F", "Message starts with the keyword"),
                            ("O", "Message contains only the keyword"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("referrer_id", models.CharField(max_length=255, null=True)),
                (
                    "channel",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="triggers",
                        to="channels.channel",
                    ),
                ),
                (
                    "contacts",
                    models.ManyToManyField(related_name="triggers", to="contacts.contact"),
                ),
            ],
            options={
                "verbose_name": "Trigger",
                "verbose_name_plural": "Triggers",
            },
        ),
    ]
