# Generated by Django 5.2.2 on 2025-07-02 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contacts", "0208_squashed"),
        ("flows", "0388_squashed"),
        ("orgs", "0172_squashed"),
        ("schedules", "0030_squashed"),
        ("triggers", "0042_squashed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="trigger",
            name="created_by",
            field=models.ForeignKey(
                help_text="The user which originally created this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_creations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="trigger",
            name="exclude_groups",
            field=models.ManyToManyField(related_name="triggers_excluded", to="contacts.contactgroup"),
        ),
        migrations.AddField(
            model_name="trigger",
            name="flow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="triggers",
                to="flows.flow",
            ),
        ),
        migrations.AddField(
            model_name="trigger",
            name="groups",
            field=models.ManyToManyField(related_name="triggers_included", to="contacts.contactgroup"),
        ),
        migrations.AddField(
            model_name="trigger",
            name="modified_by",
            field=models.ForeignKey(
                help_text="The user which last modified this item",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_modifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="trigger",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="triggers",
                to="orgs.org",
            ),
        ),
        migrations.AddField(
            model_name="trigger",
            name="schedule",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="trigger",
                to="schedules.schedule",
            ),
        ),
        migrations.AddConstraint(
            model_name="trigger",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("trigger_type", "S"), _negated=True),
                    ("schedule__isnull", False),
                    ("is_active", False),
                    _connector="OR",
                ),
                name="triggers_scheduled_trigger_has_schedule",
            ),
        ),
    ]
